// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrWG-YVcvAMMsz1KeX-Y8eX8YXUSR49OU',
    appId: '1:623397062568:android:a66e19e126f7f1737d7f9d',
    messagingSenderId: '623397062568',
    projectId: 'personal-expense-app-2eea0',
    databaseURL: 'https://personal-expense-app-2eea0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personal-expense-app-2eea0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD7jepnvMTteDn4HfMgkurzayy55Soha8',
    appId: '1:623397062568:ios:93446c910b5fa45c7d7f9d',
    messagingSenderId: '623397062568',
    projectId: 'personal-expense-app-2eea0',
    databaseURL: 'https://personal-expense-app-2eea0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personal-expense-app-2eea0.appspot.com',
    androidClientId: '623397062568-hl2da9ngs89tgjfclkrh1n1srv2i1i7l.apps.googleusercontent.com',
    iosClientId: '623397062568-hj2cr6h32dd9aolj91r88sikaoj6em2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCompleteGuide',
  );
}
